In [5]:
import numpy as np 
myarray = np.array([1,2,3,4,5,6,7,8,9,10])

print(myarray)

myarray.shape
myarray.dtype
myarray[5]=50 
print(myarray)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5 50  7  8  9 10]


In [7]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
listarray.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int64')

In [9]:
dictarray=np.array({1:'a',2:'b',3:'c'})
print(dictarray)
dictarray.dtype

{1: 'a', 2: 'b', 3: 'c'}


dtype('O')

In [31]:
zeros = np.ones((5,5))
print(zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
zeros = np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
rng =np.arange(10)
print(rng)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
lspace = np.linspace(1,5,10)
print(lspace)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [35]:
emp = np.empty((4,6))
print(emp)

[[1.03977872e-311 7.16395186e-322 0.00000000e+000 0.00000000e+000
  3.44901217e-307 1.16096346e-028]
 [9.82205649e+252 1.11789342e+253 1.12594083e-153 6.01347002e-154
  3.21867040e-057 7.11745808e-038]
 [3.64468655e-086 4.66726146e-062 1.04102738e-042 6.74351023e-067
  4.07685730e+223 1.51979061e-047]
 [9.72380871e-072 1.28977971e-057 2.21420214e-052 6.01347033e-154
  7.78045906e-143 8.46781366e+136]]


In [36]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
print(listarray.sum(axis=0))
print(listarray.sum(axis=1))

listarray.T  # row to column and column to row

listarray.flat
for i in listarray.flat:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
1
2
3
4
5
6
7
8
9


In [37]:
one = np.array([1,2,30,44,5,26,17,8,9,10])
print(one.argmax())
print(one.argmin())
print(one.argsort())

3
0
[0 1 4 7 8 9 6 5 2 3]


In [46]:
np.random.randint(1,100,5)


array([90, 15, 18, 10, 42], dtype=int32)